In [2]:
import numpy as np

In [ ]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [ ]:
type(a)

numpy.ndarray

In [ ]:
dir(a)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__class_getitem__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__dlpack__',
 '__dlpack_device__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',

In [ ]:
a.shape

(3,)

In [ ]:
a.ndim

1

In [ ]:
a.size

3

In [ ]:
a = 16
type(a)

int

In [ ]:
a.dtype

dtype('int64')

In [ ]:
a.itemsize

8

In [ ]:
b = np.array([1.,2,3])
b

array([1., 2., 3.])

In [ ]:
b.dtype

dtype('float64')

In [ ]:
c = np.array([1,2,3], dtype=np.float64)
c.dtype

dtype('float64')

In [ ]:
print(c.astype(int))

[1 2 3]


In [ ]:
print(c.astype(str))

['1.0' '2.0' '3.0']


In [ ]:
a[2]

3

In [ ]:
a = np.zeros(3)
b = np.ones(3, dtype=np.int64)

print(b)

[1 1 1]


In [ ]:
c = np.zeros_like(b)
print(c)

[0 0 0]


In [ ]:
d = np.arange(0, 10, 2)
print(d)

[0 2 4 6 8]


In [ ]:
d= np.linspace(0, 9, 10)
print(d)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [ ]:
a = np.array([1,2,3])
b = np.array([1,2,3])

In [ ]:
print(a-b)

[0 0 0]


In [ ]:
print(a*b)

[1 4 9]


In [ ]:
print(a**b)

[ 1  4 27]


In [ ]:
np.sin(a)

array([0.84147098, 0.90929743, 0.14112001])

In [ ]:
print(a > b)

[False False False]


In [ ]:
predicate = a > 1
np.any(predicate)

True

In [ ]:
np.all(predicate)

False

In [ ]:
a += 1
print(a)

[2 3 4]


In [3]:
a = np.array([1,2.1,3])
b = np.array([1,4,3])

In [4]:
a.mean()

2.033333333333333

In [5]:
a.max()

3.0

In [6]:
a.min()

1.0

In [7]:
np.sort(a)

array([1. , 2.1, 3. ])

In [9]:
np.hstack((a, b))

array([1. , 2.1, 3. , 1. , 4. , 3. ])

In [11]:
print(a[2:6])

[3.]


In [12]:
print(a[::-1])

[3.  2.1 1. ]


In [13]:
b = a[:]
print(b)

[1.  2.1 3. ]


In [14]:
a[1] = 0.1

In [15]:
print(a[1])
print(b[1])

0.1
0.1


In [18]:
b = a.copy()

In [20]:
b[0] = 100
print(a[0])
print(b[0])

1.0
100.0


In [22]:
# создать массив размера a булевских значений
# заполнить true если a[i] > 1

# [False False True]

b = a > 1
print(b)

[False False  True]


In [23]:
print(a[b])

[3.]


In [27]:
x = np.linspace(-2*np.pi, 2*np.pi, 100)
y_sin = np.sin(x)**2
y_cos = np.cos(x)**2

print((y_sin + y_cos).round())
np.all((y_sin + y_cos).round() == 1)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1.]


True

In [31]:
a = np.array([[1, 2], [2, 3]])
print(a)

[[1 2]
 [2 3]]


In [30]:
a = np.array([1,2.1,3])
b = np.array([1,4,3])
print(a*b)

[1.  8.4 9. ]


In [36]:
a = np.array([[1, 2], [2, 3], [-1, -2]])
print(a)
b = np.array([[1, 2, 3], [2, 3, 1]])
print(b)

print(a@b) # матричное произведение

[[ 1  2]
 [ 2  3]
 [-1 -2]]
[[1 2 3]
 [2 3 1]]
[[ 5  8  5]
 [ 8 13  9]
 [-5 -8 -5]]


In [37]:
a = np.array([[1, 2], [2, 3], [-1, -2]])
print(a)
b = np.array([[1, 2], [2, 3], [-1, -2]])
print(b)

print(a*b) # поэлементное произведение

[[ 1  2]
 [ 2  3]
 [-1 -2]]
[[ 1  2]
 [ 2  3]
 [-1 -2]]
[[1 4]
 [4 9]
 [1 4]]


In [38]:
print(b.T)

[[ 1  2 -1]
 [ 2  3 -2]]


![]('https://wikimedia.org/api/rest_v1/media/math/render/svg/f8852833a56a9b55fdf5d6b2521eaec45274bab8')

In [ ]:
# ax = v
np.linalg.solve(a, v)

In [40]:
# f(x) =  e ^ (-x^2) - [0, 1]

from scipy.integrate import quad

def f(x):
  return np.exp(-x**2)

res, err = quad(f, 0, 1)
print(quad(f, 0, 1))

(0.7468241328124271, 8.291413475940725e-15)


In [41]:
np.savetxt('result.csv', b, delimiter=';')